services:
  db:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./sql_tables:/docker-entrypoint-initdb.d
  
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db_data: